### PR TITLE
Draft internal API spec

### PR DESCRIPTION
**Pull request by zachlipton**
I'm not 100% positive on every detail here, but this attempts to lay out all the data types and realigns them all around the spreadsheet, the data dictionary, our design doc, some clarifying discussions, and the existing public API. It's very much a draft and could use a few more pairs of eyes. Suggestions extremely welcome

The easiest way to view this is to look at https://studio-ws.apicur.io/sharing/9aef82b7-4132-4603-add0-39cf27415dae, which will present everything in a nice little viewer.   

Still missing:
- Security/API key for posting
- Some examples (easier to copy/paste once the spec is firmed up and we have an initial implementation)
- The internal API file contains a cross-reference to the shared data types API file to pull in CoreData and StateInfo. This URL includes the branch name so that everything can be easily viewed, but that will need to be updated.

### CODE REVIEW

**Comment by joshuaellinger** [comment]
Looks good!

Comment around batches (/batches)

1. How do we add race data in the future?  Do we want to reuse the same /batches endpoint? 

If so, we should put more information in the POST.

2. I think that GET /batches/{id} should mirror the POST payload.

3. The body on /batches/{id}/publish is unnecessary.  If you want to be overly picky, we might want to make it be a PUT but I personally don't like that.

4. I need to review and update the field names in the POST to match data dictionary changes form Kevin

**Comment by joshuaellinger** [comment]
Also, I'm not convinced that we really want publish states in lock-step with core-data.  They change rarely.  We didn't really design the DB to handle tracking a slow changing table like that.

Probably, the best thing to do is push it every time -- better to have it be redundant than want it later and not be able to get it.

**Comment by joshuaellinger** [comment]
Do we want a way to remove unpublished data, if nothing else for testing?

I'm thinking a DELETE /batches/{id} endpoint that fails if published = True.

**Comment by joshuaellinger** [comment]
And do you want to change the publish step to:
    PUT /batches/{id} with payload { "publish": true }.

It is a little more rest like then and it eliminates the need for a specific "publish" endpoint.  I don't really have a preference.

**Comment by joshuaellinger** [comment]
Finally, it might be implicit but there is a version number in the URL, right?

**Comment by zachlipton** [comment]
Yeah there are a lot of thorny questions this exercise brought up, and you hit on most of them.

> How do we add race data in the future? Do we want to reuse the same /batches endpoint?

My thought was that every batch would have a data type associated with it. For the moment, the data type of all batches is assumed to be coreData. We could make that explicit in the DB now, but it's easy enough to add a column for that in the future. So we'd use the same endpoint, but with a raceData object attached. The alternative is to have batches_coreData, batches_raceData, etc... tables, but that seems duplicative. I'm thinking that it's cleanest to restrict a batch to only having one data type associated though; no batches containing more than one type of data (except state metadata maybe, see below).

> The body on /batches/{id}/publish is unnecessary. If you want to be overly picky, we might want to make it be a PUT but I personally don't like that.

Which body? The ReDoc display makes it a bit unclear; there's no request body—just the batch ID in the url. The bit on the right there is just the response (the response is pretty unnecessary, but it's the same thing you get when you do a push so I kept it for consistency). I went back and forth on the publish API, because it requires you to store the batch ID somewhere to publish it. That seemed safest (impossible to introduce new data during publication or publish the wrong thing), but I'm not convinced it's right.

> Also, I'm not convinced that we really want publish states in lock-step with core-data. They change rarely. We didn't really design the DB to handle tracking a slow changing table like that. Probably, the best thing to do is push it every time -- better to have it be redundant than want it later and not be able to get it.

Yeah. This was the extra annoying one. I started a little discussion in #data-layer-changes but nobody was that interested. There are a few options:

1. Treat StateInfo as a separate versioned data type (like race data will be in the future). There's a separate menu option to push/preview and publish it, every push of new state data gets a batch, etc... Architecturally pure, but not necessary really.
2. Treat StateInfo as a separate unversioned data type. There's a separate "publish state data" menu option that pushes up just the state data, and those values are immediately written to the DB, but without being managed in batches. 
3. Treat StateInfo as an extra chunk of metadata that rides along with core data. A regular daily push of core data automatically includes the latest state information, and that data is immediately written to the DB's states table when a new batch is pushed. 

I went with option #3 because that seems like how we're basically operating now, and it eliminates the "made a change and forgot to push it" problem, but could easily be convinced it should work differently. @julia326 curious if you have opinions here.

> I'm thinking a DELETE /batches/{id} endpoint that fails if published = True.

Probably not something to expose in the Apps Script, but I could see that useful for testing, sure. I think the implicit assumption should be that deleting a batch also deletes the associated data, and agreed that there's no deleting of published data. There's always the option to manually unpublish data just by setting published=false in the database.

> Finally, it might be implicit but there is a version number in the URL, right?

ReDoc does its damnedest to hide it from you, but yes. If you click on the endpoints in the right column, it expands to show the full URL, e.g. `https://internalapi.covidtracking.com/api/v1/batches`. I am not attached to `internalapi` as a subdomain but put it in for now.

> And do you want to change the publish step to: `PUT /batches/{id} with payload { "publish": true }.`

I was thinking I'd just avoid the payload for publishing entirely. It's not as RESTful, but I liked the idea of really explicitly putting publish in the URL to make the action clear and avoid any confusion about what's going to happen.

Some revisions coming soon.

**Comment by julia326** [comment]
This is awesome! A few initial thoughts:

- We just chatted offline about this, but having the `states` endpoint not be under `public` is a bit confusing, since states info is also served somewhere in the public API. 
- If we mirror how the public API does it, then we could have endpoints like `/states/info`, `states/current` and `states/daily` to serve. This means we lose the `public` API organization potentially, but I wonder if the consistency is worth it
- in the `PushContext` for a batch push: I think we decided to walk away from the boolean `daily` in favor of a string `dataEntryType` so we don't lock into a daily-based data model? (Esp for other data types collected e.g. weekly or however)
- In theory, if we want to be very RESTful, we should return the POST payload after publishing it - but I'm not super attached to this
- We don't necessarily need to add this now, but what would a historical edit endpoint look like? I'm guessing this would be part of the PushContext?

**Comment by zachlipton** [comment]
Missed a really important one, which becomes pretty obvious when you try to use it and realize you have a pile of nameless data:

- [x] the coreData elements in the POST /batches call need to contain the state name

**Comment by zachlipton** [comment]
- [x] coreData (and every other type of data) needs dataDate to report the date the data is for.
- [x] Preview endpoint(s)/a preview flag on the regular GET endpoints to expose the data in the preview state (needs a brief conversation about the exact data entry flow to understand how this will be used)

**Comment by zachlipton** [comment]
Updated preview link is https://studio-ws.apicur.io/sharing/9aef82b7-4132-4603-add0-39cf27415dae

**Comment by zachlipton** [comment]
Merged following discussion in #database-build. There will surely be revisions in future PRs.

**Pull request merged**
